[package]
name = "btrfs-auto-snapshot"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
clap = { version = "4.5.32", features = ["derive"] }
clap_complete = "4.5.47"
colog = "1.3.0"
log = "0.4.27"
thiserror = "2.0.12"
